# Generated by Django 3.1.7 on 2021-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_dob', models.DateTimeField()),
                ('animal_type', models.CharField(choices=[('SN', 'Snake'), ('GK', 'Gecko')], default='SN', max_length=2)),
            ],
        ),
    ]
