# Generated by Django 3.1.7 on 2021-03-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210313_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Snake_Feeding',
            fields=[
                ('feeding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.feeding')),
                ('quantity_fed', models.IntegerField()),
            ],
            bases=('records.feeding',),
        ),
    ]
