# Generated by Django 3.1.7 on 2021-03-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_feeding_snake_feeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeFeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_date', models.DateField()),
                ('quantity_fed', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.animal')),
            ],
        ),
        migrations.RemoveField(
            model_name='snake_feeding',
            name='feeding_ptr',
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
        migrations.DeleteModel(
            name='Snake_Feeding',
        ),
    ]
