# Generated by Django 3.1.7 on 2021-03-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_snakefeeding_new_thing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakefeeding',
            name='new_thing',
        ),
    ]
