# Generated by Django 3.1.7 on 2021-03-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20210313_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeckoFeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_date', models.DateField()),
                ('quantity_given', models.IntegerField()),
                ('quantity_eaten', models.IntegerField(null=True)),
                ('type_of_food', models.CharField(choices=[('MW', 'Mealworms')], max_length=2)),
                ('animal', models.ForeignKey(limit_choices_to={'animal_type': 'GK'}, on_delete=django.db.models.deletion.CASCADE, to='records.animal')),
            ],
        ),
    ]
