# Generated by Django 3.1.7 on 2021-03-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_geckofeeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='cleaning_frequency',
            field=models.IntegerField(default=6, verbose_name='Cleaning frequency (weeks)'),
        ),
        migrations.CreateModel(
            name='AnimalCleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cleaned', models.DateField()),
                ('type_of_clean', models.CharField(choices=[('SP', 'Spot Clean'), ('FU', 'Full Clean')], default='SP', max_length=2)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.animal')),
            ],
        ),
    ]
