# Generated by Django 3.1.7 on 2021-03-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20210313_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckofeeding',
            name='coating',
            field=models.CharField(choices=[('RP', 'Repton'), ('CA', 'Calcium'), ('NO', 'None')], default='NO', max_length=2),
        ),
    ]
