# Generated by Django 3.1.7 on 2021-03-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_geckofeeding_coating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.IntegerField(verbose_name='Weight (grams)')),
                ('food_regurgitated', models.BooleanField()),
                ('comments', models.CharField(max_length=10000)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.animal')),
            ],
        ),
    ]
