# Generated by Django 3.1.7 on 2021-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_animalhealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalhealth',
            name='comments',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Weight (grams)'),
        ),
    ]
