# Generated by Django 3.1.7 on 2021-03-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20210320_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gecko',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.animal')),
                ('_type', models.CharField(default='GK', max_length=2)),
                ('feeding_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=6)),
            ],
            bases=('records.animal',),
        ),
        migrations.CreateModel(
            name='NavBarHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.animal')),
                ('_type', models.CharField(default='SN', max_length=2)),
                ('feeding_frequency', models.IntegerField(default=14, verbose_name='Feeding Frequency (days)')),
            ],
            bases=('records.animal',),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='comments',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight (grams)'),
        ),
    ]
