# Generated by Django 3.1.7 on 2021-03-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20210321_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_type',
        ),
        migrations.AlterField(
            model_name='geckofeeding',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.gecko'),
        ),
        migrations.AlterField(
            model_name='snakefeeding',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.snake'),
        ),
    ]
