# Generated by Django 3.1.7 on 2021-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20210322_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gecko',
            name='feeding_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=5),
        ),
    ]
