# Generated by Django 3.1.7 on 2021-03-24 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20210322_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='feedings_started',
            field=models.DateField(default=datetime.date(2021, 3, 24)),
        ),
    ]
