# Generated by Django 3.1.7 on 2021-04-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_auto_20210329_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geckofeeding',
            name='quantity_eaten',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
