# Generated by Django 3.1.7 on 2021-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auto_20210401_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhealth',
            name='food_refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animalhealth',
            name='shed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='food_regurgitated',
            field=models.BooleanField(default=False),
        ),
    ]
