# Generated by Django 3.1.7 on 2022-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20210404_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='spot_cleaning_frequency',
            field=models.IntegerField(default=6, verbose_name='Spot cleaning frequency (weeks)'),
        ),
    ]
