# Generated by Django 3.1.7 on 2022-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_animal_spot_cleaning_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='spot_cleaning_frequency',
            field=models.IntegerField(default=2, verbose_name='Spot cleaning frequency (weeks)'),
        ),
    ]
