# Generated by Django 3.1.7 on 2022-08-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_gecko_feeding_day_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gecko',
            name='feeding_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2),
        ),
        migrations.AlterField(
            model_name='gecko',
            name='feeding_day_2',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=5),
        ),
    ]
