# Generated by Django 3.1.7 on 2022-08-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_auto_20220825_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gecko',
            name='feedings_started',
        ),
    ]
